large frontend additions
dartmouth-cs98-23f/arena pull request #43
Opened 2023-11-03 21:04 UTC by mahirs0309

2023-11-03 21:08 UTC, ianmkim requested changes

2023-11-03 21:08 UTC, ianmkim commented on bazel-testlogs
> +/private/var/tmp/_bazel_mahir/3a50be9f9914f6246922ce5499671600/execroot/arena/bazel-out/darwin_arm64-fastbuild/testlogs
these bazel files should not be committed, please add them to gitignore

2023-11-03 21:08 UTC, ianmkim commented on frontend/arena_frontend/.gitignore
> +# Learn more https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files
gitignore should be at the root of the repo, not just in the frontend

2023-11-03 21:08 UTC, ianmkim commented on frontend/arena_frontend/screens/PendingBetsScreen.js
Empty file?

2023-11-04 17:18 UTC, mahirs0309 commented on frontend/arena_frontend/screens/PendingBetsScreen.js
yeah its chill will fill it later

2023-11-04 17:18 UTC, mahirs0309 commented on frontend/arena_frontend/screens/PendingBetsScreen.js
unless u want me to delete it

2023-11-04 21:09 UTC, ianmkim commented on frontend/arena_frontend/screens/PendingBetsScreen.js
Nah all good

2023-11-04 21:10 UTC, ianmkim approved these changes

2023-11-05 20:34 UTC, ianmkim approved these changes

2023-11-05 20:46 UTC, merged