Ravin frontend
dartmouth-cs98-23f/arena pull request #56
Opened 2023-11-08 20:50 UTC by RavinAnderson

Oauth Skeleton

2023-11-08 21:02 UTC, ianmkim requested changes

2023-11-08 21:02 UTC, ianmkim commented on backend/src/routers/index.py
> +    client_id="988417806604-ggnkhrhere0el8b4r3ehko3ncmt8181r.apps.googleusercontent.com",
@jeffreylam4 this has to be an env var. See my example in the database.py how I retrieve database credentials

2023-11-08 21:02 UTC, ianmkim commented on backend/src/routers/index.py
> +        return HTMLResponse(f'<p>Hello {name}!</p><a href=/logout>Logout</a>')
we don't want this to be the index, the index should stay as is

2023-11-08 21:02 UTC, ianmkim commented on backend/src/routers/index.py
> +    # You can now create a user session or a JWT token
we should be checking for dartmouth edu address and create the token

2023-11-08 21:02 UTC, ianmkim commented on bazel-arena
> +/private/var/tmp/_bazel_ravinanderson/5bdab95fb3f67d05f8432243c2b13f2e/execroot/arena
This should be part of the .gitignore

2023-11-10 00:50 UTC, jeffreylam4 approved these changes
Great work

2023-11-10 00:51 UTC, merged